#
# EEPROM drivers
#
drivers-eeprom := $(srctree)/drivers/eeprom

c_src-$(CONFIG_EEPROM_AVR) += $(drivers-eeprom)/eeprom-avr.c
c_src-$(CONFIG_EEPROM_CY15B004J) += $(drivers-eeprom)/eeprom-cy15b004j.c
