#
# Staging pwm drivers
#
staging-drivers-pwm := $(srctree)/staging/drivers/pwm

c_src-$(CONFIG_PWM_MC9S08PTXX_FTM) += $(staging-drivers-pwm)/pwm-mc9s08ptxx_ftm.c
c_src-$(CONFIG_PWM_N76E003) += $(staging-drivers-pwm)/pwm-n76e003.c
c_src-$(CONFIG_PWM_CH552) += $(staging-drivers-pwm)/pwm-ch552.c
