#
# Clocks makefile
#
drivers-clock := $(srctree)/drivers/clock

c_src-$(CONFIG_CLOCK_ATMEGA2560) += $(drivers-clock)/clock-atmega2560.c
c_src-$(CONFIG_CLOCK_ATMEGA328P) += $(drivers-clock)/clock-atmega328p.c
c_src-$(CONFIG_CLOCK_F28379X) += $(drivers-clock)/clock-f28379x.c
c_src-$(CONFIG_CLOCK_GD32VF103) += $(drivers-clock)/clock-gd32vf103.c
c_src-$(CONFIG_CLOCK_PIC32MX) += $(drivers-clock)/clock-pic32mx.c
c_src-$(CONFIG_CLOCK_RP2040) += $(drivers-clock)/clock-rp2040.c
c_src-$(CONFIG_CLOCK_ATSAM3X) += $(drivers-clock)/clock-sam3x_pmc.c
c_src-$(CONFIG_CLOCK_ATSAME5X) += $(drivers-clock)/clock-same5x.c
c_src-$(CONFIG_CLOCK_STM32H7XX) += $(drivers-clock)/clock-stm32h7xx.c
c_src-$(CONFIG_CLOCK_TINYAVR) += $(drivers-clock)/clock-tinyavr.c
c_src-$(CONFIG_CLOCK_RENESAS_RA4) += $(drivers-clock)/clock-renesas_ra4.c
