#
# GPIO drivers makefile
#
drivers-gpio := $(srctree)/drivers/gpio

c_src-$(CONFIG_GPIO_AVR) += $(drivers-gpio)/gpio-avr.c
c_src-$(CONFIG_GPIO_GD32VF103) += $(drivers-gpio)/gpio-gd32vf103.c
c_src-$(CONFIG_GPIO_PIC32MX) += $(drivers-gpio)/gpio-pic32mx.c
c_src-$(CONFIG_GPIO_RP2040) += $(drivers-gpio)/gpio-rp2040_sio.c
c_src-$(CONFIG_GPIO_ATSAM3X) += $(drivers-gpio)/gpio-sam3x_pio.c
c_src-$(CONFIG_GPIO_ATSAME5X) += $(drivers-gpio)/gpio-same5x.c
c_src-$(CONFIG_GPIO_STM32H7XX) += $(drivers-gpio)/gpio-stm32h7xx.c
c_src-$(CONFIG_GPIO_TI_F28X) += $(drivers-gpio)/gpio-ti_f28x.c
c_src-$(CONFIG_GPIO_TINYAVR) += $(drivers-gpio)/gpio-tinyavr.c
