#
# WD drivers makefile
#
drivers-wd := $(srctree)/drivers/wd

c_src-$(CONFIG_WD_AVR) += $(drivers-wd)/wd-avr.c
c_src-$(CONFIG_WD_GD32VF103_FWDGT) += $(drivers-wd)/wd-gd32vf103_fwdgt.c
c_src-$(CONFIG_WD_PIC32MX) += $(drivers-wd)/wd-pic32mx.c
c_src-$(CONFIG_WD_RP2040) += $(drivers-wd)/wd-rp2040.c
c_src-$(CONFIG_WD_ATSAM3X) += $(drivers-wd)/wd-sam3x.c
c_src-$(CONFIG_WD_ATSAME5X) += $(drivers-wd)/wd-same5x.c
c_src-$(CONFIG_WD_STM32H7XX_IWDG) += $(drivers-wd)/wd-stm32h7xx_iwdg.c
c_src-$(CONFIG_WD_TI_F28X) += $(drivers-wd)/wd-ti_f28x.c
c_src-$(CONFIG_WD_TINYAVR) += $(drivers-wd)/wd-tinyavr.c
