#
# Staging gpio drivers
#
staging-drivers-gpio := $(srctree)/staging/drivers/gpio

c_src-$(CONFIG_GPIO_NXP_SIU) += $(staging-drivers-gpio)/gpio-nxp_siu.c
c_src-$(CONFIG_GPIO_NXP_SIUL2) += $(staging-drivers-gpio)/gpio-nxp_siul2.c
c_src-$(CONFIG_GPIO_RENESAS_RA4) += $(staging-drivers-gpio)/gpio-renesas_ra4.c
