#
# Staging gpio drivers
#
staging-drivers-gpio := $(srctree)/staging/drivers/gpio

c_src-$(CONFIG_GPIO_8051) += $(staging-drivers-gpio)/gpio-8051.c
c_src-$(CONFIG_GPIO_N76E003) += $(staging-drivers-gpio)/gpio-n76e003.c
c_src-$(CONFIG_GPIO_STM32F10XXX) += $(staging-drivers-gpio)/gpio-stm32f10xxx.c
c_src-$(CONFIG_GPIO_WCH_CH32X) += $(staging-drivers-gpio)/gpio-wch_ch32x.c
c_src-$(CONFIG_GPIO_MC9S08PTXX) += $(staging-drivers-gpio)/gpio-mc9s08ptxx.c
