#
# MISC drivers makefile
#
drivers-misc :=  $(srctree)/drivers/misc

c_src-$(CONFIG_MISC_PIC32MX) += $(drivers-misc)/misc-pic32mx.c
c_src-$(CONFIG_MISC_RP2040_RESET) += $(drivers-misc)/misc-rp2040_reset.c
c_src-$(CONFIG_MISC_STM32H7XX_DMAMUX) += $(drivers-misc)/misc-stm32h7xx_dmamux.c
