#
# ADC makefile
#
drivers-adc := $(srctree)/drivers/adc

c_src-$(CONFIG_ADC_AVR) += $(drivers-adc)/adc-avr.c
c_src-$(CONFIG_ADC_PIC32MX) += $(drivers-adc)/adc-pic32mx.c
c_src-$(CONFIG_ADC_RP2040) += $(drivers-adc)/adc-rp2040.c
c_src-$(CONFIG_ADC_SAM3X) += $(drivers-adc)/adc-sam3x.c
c_src-$(CONFIG_ADC_SAME5X) += $(drivers-adc)/adc-same5x.c
c_src-$(CONFIG_ADC_TINYAVR) += $(drivers-adc)/adc-tinyavr.c
c_src-$(CONFIG_ADC_TI_TYPE4) += $(drivers-adc)/adc-ti_type4.c
c_src-$(CONFIG_ADC_RENESAS_RA4) += $(drivers-adc)/adc-renesas_ra4.c
c_src-$(CONFIG_ADC_NXP_SAR) += $(drivers-adc)/adc-nxp_sar.c
c_src-$(CONFIG_ADC_STM32H7XX_SAR) += $(drivers-adc)/adc-stm32h7xx_sar.c
c_src-$(CONFIG_ADC_ATMEL_AFEC) += $(drivers-adc)/adc-atmel_afec.c
