#
# ADC makefile
#
drivers-adc := $(srctree)/drivers/adc

c_src-$(CONFIG_ADC_AVR) += $(drivers-adc)/adc-avr.c
c_src-$(CONFIG_ADC_PIC32MX) += $(drivers-adc)/adc-pic32mx.c
c_src-$(CONFIG_ADC_RP2040) += $(drivers-adc)/adc-rp2040.c
c_src-$(CONFIG_ADC_SAM3X) += $(drivers-adc)/adc-sam3x.c
c_src-$(CONFIG_ADC_SAME5X) += $(drivers-adc)/adc-same5x.c
c_src-$(CONFIG_ADC_TINYAVR) += $(drivers-adc)/adc-tinyavr.c
c_src-$(CONFIG_ADC_TI_TYPE4) += $(drivers-adc)/adc-ti_type4.c
