#
# DMA drviers makefile
#
drivers-dma := $(srctree)/drivers/dma

c_src-$(CONFIG_DMA_GD32VF103) += $(drivers-dma)/dma-gd32vf103.c
c_src-$(CONFIG_DMA_RP2040) += $(drivers-dma)/dma-rp2040.c
c_src-$(CONFIG_DMA_ATSAME5X) += $(drivers-dma)/dma-same5x.c
c_src-$(CONFIG_DMA_STM32H7XX) += $(drivers-dma)/dma-stm32h7xx.c
c_src-$(CONFIG_DMA_TI_F28X) += $(drivers-dma)/dma-ti_f28x.c
