#
# Staging clock drivers
#
staging-drivers-clock := $(srctree)/staging/drivers/clock

c_src-$(CONFIG_CLOCK_MPC574XX) += $(staging-drivers-clock)/clock-mpc574xx.c
c_src-$(CONFIG_CLOCK_NXP_SIU) += $(staging-drivers-clock)/clock-nxp_siu.c
