#ifndef PICORTOSCONFIG_H
#define PICORTOSCONFIG_H

/* CLOCKS */
#define CONFIG_SYSCLK_HZ        200000000ul
#define CONFIG_TICK_HZ          1000ul

/* TASKS */
#define CONFIG_TASK_COUNT       10

/* STACK */
#define CONFIG_DEFAULT_STACK_COUNT 128

/* IPCs */
#define CONFIG_DEADLOCK_COUNT 20000

#endif
