#ifndef PICORTOS_CONFIG_H
#define PICORTOS_CONFIG_H

/* CLOCKS */
#define CONFIG_SYSCLK_HZ 250
#define CONFIG_TICK_HZ   10

/* TASKS */
#define CONFIG_TASK_COUNT 5

#define CONFIG_DEFAULT_STACK_COUNT 128

#endif
