#
# Staging spi drivers
#
staging-drivers-spi := $(srctree)/staging/drivers/spi

c_src-$(CONFIG_SPI_MC9S08PTXX) += $(staging-drivers-spi)/spi-mc9s08ptxx.c
c_src-$(CONFIG_SPI_N76E003) += $(staging-drivers-spi)/spi-n76e003.c
