#
# Staging flash drivers
#
staging-drivers-flash := $(srctree)/staging/drivers/flash

c_src-$(CONFIG_FLASH_NXP_C55FMC) += $(staging-drivers-flash)/flash-nxp_c55fmc.c
c_src-$(CONFIG_FLASH_ATSAM3X) += $(staging-drivers-flash)/flash-sam3x.c
