#
# TWI drivers makefile
#
drivers-twi := $(srctree)/drivers/twi

c_src-$(CONFIG_TWI_ATMEL_SERCOM) += $(drivers-twi)/twi-atmel_sercom.c
c_src-$(CONFIG_TWI_AVR) += $(drivers-twi)/twi-avr.c
c_src-$(CONFIG_TWI_DW_APB_I2C) += $(drivers-twi)/twi-dw_apb_i2c.c
c_src-$(CONFIG_TWI_PIC32MX) += $(drivers-twi)/twi-pic32mx.c
c_src-$(CONFIG_TWI_ATSAM3X) += $(drivers-twi)/twi-sam3x.c
c_src-$(CONFIG_TWI_TI_F28X) += $(drivers-twi)/twi-ti_f28x.c
