#
# Flash drivers
#
drivers-flash-ext := $(srctree)/drivers/flash-ext

c_src-$(CONFIG_FLASH_EXT_SST26VF) += $(drivers-flash-ext)/flash-ext-sst26vf.c
c_src-$(CONFIG_FLASH_EXT_S25FL1) += $(drivers-flash-ext)/flash-ext-s25fl1.c
