#
# SPI drivers makefile
#
drivers-spi := $(srctree)/drivers/spi

c_src-$(CONFIG_SPI_ARM_PL022) += $(drivers-spi)/spi-arm_pl022.c
c_src-$(CONFIG_SPI_ATMEL_SERCOM) += $(drivers-spi)/spi-atmel_sercom.c
c_src-$(CONFIG_SPI_AVR) += $(drivers-spi)/spi-avr.c
c_src-$(CONFIG_SPI_AVR_USART) += $(drivers-spi)/spi-avr_usart.c
c_src-$(CONFIG_SPI_GD32VF103) += $(drivers-spi)/spi-gd32vf103.c
c_src-$(CONFIG_SPI_PIC32MX) += $(drivers-spi)/spi-pic32mx.c
c_src-$(CONFIG_SPI_ATSAM3X) += $(drivers-spi)/spi-sam3x.c
c_src-$(CONFIG_SPI_STM32H7XX) += $(drivers-spi)/spi-stm32h7xx.c
c_src-$(CONFIG_SPI_TI_F28X) += $(drivers-spi)/spi-ti_f28x.c
c_src-$(CONFIG_SPI_TINYAVR) += $(drivers-spi)/spi-tinyavr.c
c_src-$(CONFIG_SPI_RENESAS_RA4) += $(drivers-spi)/spi-renesas_ra4.c
