#
# Flash drivers
#
drivers-flash := $(srctree)/drivers/flash

c_src-$(CONFIG_FLASH_GD32VF103) += $(drivers-flash)/flash-gd32vf103.c
c_src-$(CONFIG_FLASH_PIC32MX) += $(drivers-flash)/flash-pic32mx.c
c_src-$(CONFIG_FLASH_SAME5X) += $(drivers-flash)/flash-same5x.c
