#
# Staging wd drivers
#
staging-drivers-wd := $(srctree)/staging/drivers/wd

c_src-$(CONFIG_WD_RENESAS_RA4_WDT) += $(staging-drivers-wd)/wd-renesas_ra4_wdt.c
c_src-$(CONFIG_WD_MC9S08PTXX_WDOG) += $(staging-drivers-wd)/wd-mc9s08ptxx.c
