# IPCs makefile
ipc := $(srctree)/ipc

c_src-$(CONFIG_FUTEX) += $(ipc)/picoRTOS_futex.c
c_src-$(CONFIG_MUTEX) += $(ipc)/picoRTOS_mutex.c
c_src-$(CONFIG_COND) += $(ipc)/picoRTOS_cond.c
c_src-$(CONFIG_QUEUE) += $(ipc)/picoRTOS_queue.c
