#
# PWM drivers makefile
#
drivers-pwm := $(srctree)/drivers/pwm

c_src-$(CONFIG_PWM_AVR) += $(drivers-pwm)/pwm-avr.c
c_src-$(CONFIG_PWM_GD32VF103) += $(drivers-pwm)/pwm-gd32vf103.c
c_src-$(CONFIG_PWM_PIC32MX) += $(drivers-pwm)/pwm-pic32mx.c
c_src-$(CONFIG_PWM_RP2040) += $(drivers-pwm)/pwm-rp2040.c
c_src-$(CONFIG_PWM_ATSAM3X) += $(drivers-pwm)/pwm-sam3x.c
c_src-$(CONFIG_PWM_ATSAM3X_TC) += $(drivers-pwm)/pwm-sam3x_tc.c
c_src-$(CONFIG_PWM_ATSAME5X) += $(drivers-pwm)/pwm-same5x_tc.c
c_src-$(CONFIG_PWM_STM32H7XX) += $(drivers-pwm)/pwm-stm32h7xx_tim.c
c_src-$(CONFIG_PWM_TI_EPWM) += $(drivers-pwm)/pwm-ti_epwm.c
c_src-$(CONFIG_PWM_TINYAVR) += $(drivers-pwm)/pwm-tinyavr_tca.c
c_src-$(CONFIG_PWM_RENESAS_RA4_GPT) += $(drivers-pwm)/pwm-renesas_ra4_gpt.c
c_src-$(CONFIG_PWM_NXP_EMIOS) += $(drivers-pwm)/pwm-nxp_emios.c
