#
# MUX drivers makefile
#
drivers-mux := $(srctree)/drivers/mux

c_src-$(CONFIG_MUX_AVR) += $(drivers-mux)/mux-avr.c
c_src-$(CONFIG_MUX_GD32VF103) += $(drivers-mux)/mux-gd32vf103.c
c_src-$(CONFIG_MUX_PIC32MX) += $(drivers-mux)/mux-pic32mx.c
c_src-$(CONFIG_MUX_RP2040) += $(drivers-mux)/mux-rp2040.c
c_src-$(CONFIG_MUX_ATSAM3X) += $(drivers-mux)/mux-sam3x_pio.c
c_src-$(CONFIG_MUX_ATSAME5X) += $(drivers-mux)/mux-same5x.c
c_src-$(CONFIG_MUX_STM32H7XX) += $(drivers-mux)/mux-stm32h7xx.c
c_src-$(CONFIG_MUX_TI_F28X) += $(drivers-mux)/mux-ti_f28x.c
c_src-$(CONFIG_MUX_TINYAVR) += $(drivers-mux)/mux-tinyavr.c
c_src-$(CONFIG_MUX_RENESAS_RA4) += $(drivers-mux)/mux-renesas_ra4.c
c_src-$(CONFIG_MUX_NXP_SIUL2) += $(drivers-mux)/mux-nxp_siul2.c
c_src-$(CONFIG_MUX_NXP_SIU) += $(drivers-mux)/mux-nxp_siu.c
