#
# Staging mux drivers
#
staging-drivers-mux := $(srctree)/staging/drivers/mux

c_src-$(CONFIG_MUX_NXP_SIU) += $(staging-drivers-mux)/mux-nxp_siu.c
c_src-$(CONFIG_MUX_NXP_SIUL2) += $(staging-drivers-mux)/mux-nxp_siul2.c
