#
# Staging CAN drivers
#
staging-drivers-can := $(srctree)/staging/drivers/can

c_src-$(CONFIG_CAN_GD32VF103) += $(staging-drivers-can)/can-gd32vf103.c
c_src-$(CONFIG_CAN_PIC32MX) += $(staging-drivers-can)/can-pic32mx.c
c_src-$(CONFIG_CAN_ATSAME5X) += $(staging-drivers-can)/can-same5x.c
